plugins {
  id "org.jetbrains.kotlin.jvm"
  id "org.jetbrains.kotlin.plugin.serialization"
}

dependencies {
  implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"

  testImplementation "org.jetbrains.kotlin:kotlin-test:2.0.21"
  testImplementation "org.junit.jupiter:junit-jupiter:5.11.4"
}

tasks.test {
  useJUnitPlatform()
}
