import { describe, expect, it } from "vitest";

import {
  parseMobileUploadPairingQrPayload
} from "@/android-app/src/domain/pairing";
import {
  buildLectureArchiveUploadFileName,
  validateLectureArchiveNamingDraft
} from "@/android-app/src/domain/lecture-archive-naming";
import { buildMobileUploadTargetTree } from "@/android-app/src/domain/target-tree";
import { buildMobileUploadPairingQrPayload } from "@/lib/services/mobile-upload-pairing-service";
import { buildLectureArchivePdfFileName } from "@/lib/services/mobile-upload-service";

describe("android mobile upload app domain", () => {
  it("parses one valid pairing qr payload generated by the PC helper contract", () => {
    const qrPayload = buildMobileUploadPairingQrPayload({
      helperBaseUrl: "http://192.168.1.8:3000",
      pairingSessionId: "mobile-upload-pairing-1",
      pairingCode: "834271"
    });

    expect(parseMobileUploadPairingQrPayload(qrPayload)).toEqual({
      status: "valid",
      value: {
        type: "teachhelper_mobile_upload_pairing",
        helperBaseUrl: "http://192.168.1.8:3000",
        pairingSessionId: "mobile-upload-pairing-1",
        pairingCode: "834271"
      }
    });
  });

  it("rejects one invalid pairing qr payload when the json shape is unsupported", () => {
    expect(parseMobileUploadPairingQrPayload('{"type":"other"}')).toEqual({
      status: "invalid",
      errorMessage: "配对二维码内容无效"
    });
  });

  it("builds one lecture-archive upload file name that matches the workspace validation contract", () => {
    const draft = {
      studentName: "王明",
      gradeLabel: "高二",
      year: "26",
      month: "06",
      day: "04"
    };

    expect(validateLectureArchiveNamingDraft(draft)).toEqual({
      isValid: true,
      errors: {}
    });
    expect(buildLectureArchiveUploadFileName(draft)).toBe(
      buildLectureArchivePdfFileName(draft)
    );
  });

  it("returns per-field errors when the lecture-archive naming draft is invalid", () => {
    expect(
      validateLectureArchiveNamingDraft({
        studentName: "王小明同学",
        gradeLabel: "高二上",
        year: "2026",
        month: "6",
        day: "4a"
      })
    ).toEqual({
      isValid: false,
      errors: {
        studentName: "姓名不得超过4个汉字",
        gradeLabel: "年级必须是2个字符",
        year: "年份必须是2位阿拉伯数字",
        month: "月份必须是2位阿拉伯数字",
        day: "日期必须是2位阿拉伯数字"
      }
    });
  });

  it("builds one selectable target tree without duplicating folder leaves", () => {
    const tree = buildMobileUploadTargetTree([
      {
        id: "topic-1",
        name: "牛顿定律",
        path: ["专题卷库", "高中物理", "力学", "牛顿定律"],
        targetKind: "exam_folder"
      },
      {
        id: "topic-2",
        name: "动量",
        path: ["专题卷库", "高中物理", "力学", "动量"],
        targetKind: "exam_folder"
      },
      {
        id: "lecture-1",
        name: "牛顿定律主讲义",
        path: ["专题卷库", "高中物理", "力学", "牛顿定律"],
        targetKind: "exam_document"
      }
    ]);

    expect(tree).toHaveLength(1);
    expect(tree[0]).toMatchObject({
      key: "专题卷库",
      name: "专题卷库",
      path: ["专题卷库"]
    });

    const physicsNode = tree[0]?.children[0];
    const mechanicsNode = physicsNode?.children[0];
    const topicNode = mechanicsNode?.children.find((node) => node.name === "牛顿定律");
    const momentumNode = mechanicsNode?.children.find((node) => node.name === "动量");

    expect(topicNode).toMatchObject({
      name: "牛顿定律",
      selectableTarget: {
        id: "topic-1",
        targetKind: "exam_folder"
      }
    });
    expect(topicNode?.children).toEqual([
      expect.objectContaining({
        name: "牛顿定律主讲义",
        selectableTarget: expect.objectContaining({
          id: "lecture-1",
          targetKind: "exam_document"
        })
      })
    ]);
    expect(momentumNode).toMatchObject({
      name: "动量",
      selectableTarget: {
        id: "topic-2",
        targetKind: "exam_folder"
      }
    });
  });
});
